# .github/workflows/azure-backend-deploy.yml

name: Backend - gct-placementapp-gstep - Build and deploy Node.js backend to Azure Web App 

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  # Trigger only when files inside backend/ change
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install, build, and test backend
        working-directory: ./backend
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-backend
          path: backend  # Upload the entire backend folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: node-backend
          path: backend  # Restore to backend/ folder

      - name: Zip backend folder for deployment
        run: zip -r backend.zip backend

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_80828753F4874E9897BEB176827D9137 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4C68AA704A5A4BE1B59656621A78399B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D697DF00617843388B970D218602096F }}

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gct-placementapp-gstep'
          slot-name: 'Production'
          package: backend.zip
